version: '3'
services:
  mysql-docker:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdrecipes
    ports:
      - "3308:3306"

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/bdrecipes?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-docker
    ports:
      - "8080:8080"
