name: Build and Deploy Recipes App

on:
  push:
    branches: 
      - master  # Déclenche le workflow sur un push dans la branche master
  pull_request:
    branches:
      - master  # Déclenche également sur les pull requests dans master

jobs:
  build:
    runs-on: ubuntu-latest  # Exécution sur un environnement Ubuntu récent
    environment: docker  # Utilisation de l'environnement GitHub Actions défini pour les secrets Docker

    services:
      mysql:  # Service MySQL pour tester l'application
        image: mysql:8.0  # Image officielle de MySQL
        env:
          MYSQL_ROOT_PASSWORD: root  # Mot de passe root pour MySQL
          MYSQL_DATABASE: bdrecipes  # Nom de la base de données
          MYSQL_USER: root  # Utilisateur root pour MySQL
          MYSQL_PASSWORD: root  # Mot de passe root pour MySQL
        ports:
          - 3308:3306  # Redirection du port local 3308 vers le port 3306 de MySQL
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - name: Checkout code  # Récupérer le code source depuis GitHub
        uses: actions/checkout@v3

      - name: Set up JDK 17  # Installer Java 17 (nécessaire pour l'application)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'  # Utilisation de la distribution Corretto d'Amazon
          java-version: 17  # Version de Java à utiliser

      - name: Build app  # Compiler et packager l'application avec Maven
        run: |
          mvn clean package -DskipTests  # Nettoyer et compiler sans exécuter les tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3308/bdrecipes?serverTimezone=UTC  # URL de connexion à la base de données
          SPRING_DATASOURCE_USERNAME: root  # Utilisateur MySQL
          SPRING_DATASOURCE_PASSWORD: root  # Mot de passe MySQL

      - name: Log in to Docker Hub  # Se connecter à Docker Hub avec les secrets
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilisateur Docker Hub (stocké dans les secrets)
          password: ${{ secrets.DOCKER_PASSWORD }}  # Mot de passe Docker Hub ou token d'accès (stocké dans les secrets)

      - name: Build and Push Docker image  # Construire l'image Docker et la pousser vers Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .  # Utiliser le répertoire actuel comme contexte de construction
          push: true  # Pousser l'image construite vers Docker Hub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/recipes-app:latest  # Tag de l'image avec 'latest'
            ${{ secrets.DOCKER_USERNAME }}/recipes-app:${{ github.run_number }}  # Tag avec le numéro de build de GitHub Actions
